/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coronavirusbrazil;

import java.awt.Color;
import java.awt.Component;
import java.awt.Insets;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.border.EmptyBorder;
import recursos.CSVFileReader;
import recursos.Graficar;
import recursos.Recta;
import recursos.WekaController;

/**
 *
 * @author carlo
 */
public class MainFrame extends javax.swing.JFrame {
    
    private ArrayList<Recta> lineas;
    private CSVFileReader data;
    private JPanel panelCluster;
    /**
     * Creates new form MainFrame
     */
    public MainFrame(){
        panelCluster = new JPanel();
        initComponents();
        this.lineas = new ArrayList<Recta>();
        try {
            ObtenerDatos();
        } catch (Exception ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        BoxLayout boxlayout = new BoxLayout(panelCluster, BoxLayout.Y_AXIS);
        panelCluster.setLayout(boxlayout);
    }
    
    public void graficar() throws IOException, Exception {
        Graficar g = new Graficar();
        this.panelGrafica.removeAll();
        g.createDataset(lineas, data.getDia());
        g.Grafica("Grafica", "Covid-19 Brazil","Personas");
        System.out.println("entra");
        this.panelGrafica.add(g.getGrafica());
       
        this.panelCluster.removeAll();
        
        for (Recta linea : lineas) {
            JTextArea texto = new JTextArea(linea.getCluster().toString());
            texto.setTabSize(10);
            panelCluster.add(texto);
            System.out.println(linea.getCluster());
        }
        
        panelCluster.updateUI();
        repaint();
    }
    
    public void ObtenerDatos() throws IOException{
        String ruta = "CasosCOVID_Brazil.csv"; 
        data = new CSVFileReader();
        data.readData(ruta);
    }
    
    public void setDataValue(String nombreY, ArrayList<Integer> datosY, boolean isSelected){
        if(isSelected){
            WekaController.getInstance().setData("dia", nombreY, data.getDia(), datosY);
            try {
                double ecuacion[] = WekaController.getInstance().getLinearRegression().coefficients();
                Recta r = new Recta(nombreY,ecuacion[0],ecuacion[2],WekaController.getInstance().getCluster());
                this.lineas.add(r);
                graficar();
                WekaController.getInstance().setDataset(null);
            } catch (Exception ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            for (int i = 0; i < lineas.size(); i++) {
                if(lineas.get(i).getNombre()== nombreY){
                    lineas.remove(i);
                }
                this.panelGrafica.removeAll();
                try {
                    graficar();
                } catch (Exception ex) {
                    Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        panelGrafica = new javax.swing.JPanel();
        jpanel2 = new javax.swing.JPanel();
        javax.swing.JScrollPane scroll = new JScrollPane(this.panelCluster);
        checkInfectados = new javax.swing.JCheckBox();
        checkRecuperados = new javax.swing.JCheckBox();
        checkMuertos = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelGrafica.setBorder(javax.swing.BorderFactory.createTitledBorder("Regresion lineal"));

        javax.swing.GroupLayout panelGraficaLayout = new javax.swing.GroupLayout(panelGrafica);
        panelGrafica.setLayout(panelGraficaLayout);
        panelGraficaLayout.setHorizontalGroup(
            panelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );
        panelGraficaLayout.setVerticalGroup(
            panelGraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jpanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cluster"));

        javax.swing.GroupLayout jpanel2Layout = new javax.swing.GroupLayout(jpanel2);
        jpanel2.setLayout(jpanel2Layout);
        jpanel2Layout.setHorizontalGroup(
            jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );
        jpanel2Layout.setVerticalGroup(
            jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
        );

        checkInfectados.setText("Infectados");
        checkInfectados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInfectadosActionPerformed(evt);
            }
        });

        checkRecuperados.setText("Recuperados");
        checkRecuperados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkRecuperadosActionPerformed(evt);
            }
        });

        checkMuertos.setText("Muertos");
        checkMuertos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkMuertosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(checkInfectados)
                .addGap(18, 18, 18)
                .addComponent(checkRecuperados)
                .addGap(18, 18, 18)
                .addComponent(checkMuertos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkInfectados)
                    .addComponent(checkRecuperados)
                    .addComponent(checkMuertos))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGrafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkInfectadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInfectadosActionPerformed
        // TODO add your handling code here:
        setDataValue("Infectados", data.getInfectados(), this.checkInfectados.isSelected());
    }//GEN-LAST:event_checkInfectadosActionPerformed

    private void checkRecuperadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkRecuperadosActionPerformed
        // TODO add your handling code here:
        setDataValue("Recuperados", data.getRescuperados(), this.checkRecuperados.isSelected());
    }//GEN-LAST:event_checkRecuperadosActionPerformed

    private void checkMuertosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkMuertosActionPerformed
        // TODO add your handling code here:
        setDataValue("Muertos", data.getMuertos(), this.checkMuertos.isSelected());
    }//GEN-LAST:event_checkMuertosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JCheckBox checkInfectados;
    private javax.swing.JCheckBox checkMuertos;
    private javax.swing.JCheckBox checkRecuperados;
    private javax.swing.JPanel jpanel2;
    private javax.swing.JPanel panelGrafica;
    // End of variables declaration//GEN-END:variables
}
